<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2025/blob/main/Lab01/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = '5'
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [5]:
a_list = [1, 2, 2, 3.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{1, 2, 3.0, '5'}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [10]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [11]:
%pip install numpy

  Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl (12.8 MB)
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
%pip install timed-decorator

  Using cached timed_decorator-1.6.1-py3-none-any.whl.metadata (18 kB)
Using cached timed_decorator-1.6.1-py3-none-any.whl (12 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [15]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([ 3.7305233 ,  3.9742723 , -3.88301624, -4.19599835,  2.29638443,
       -4.36063981, -3.30320506,  0.8773773 , -3.94986017, -1.79772472,
       -1.53417287, -2.55186057,  0.29749262, -3.50239179,  1.57207639,
       -1.71418817, -4.38956011,  1.97488615, -4.5224696 , -1.94501075,
       -2.71889514, -2.60985587,  3.97181464, -0.85528683,  4.59971642,
       -5.24576799, -1.16313408, -3.00506542,  0.41260497, -2.35134651,
       -0.73336154, -2.91623059,  0.86168786, -4.88525436, -3.44048546,
        3.72543606,  4.15926133,  4.58684311, -4.22077173,  1.01126713,
        0.61883431,  1.52764296,  4.3252131 ,  1.74610151, -1.75858308,
       -2.72958611,  4.07453923, -2.9844482 ,  0.78658403, -2.01790372])

In [16]:
x > 0

array([ True,  True, False, False,  True, False, False,  True, False,
       False, False, False,  True, False,  True, False, False,  True,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False, False, False,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True, False])

In [17]:
x[x > 0]

array([3.7305233 , 3.9742723 , 2.29638443, 0.8773773 , 0.29749262,
       1.57207639, 1.97488615, 3.97181464, 4.59971642, 0.41260497,
       0.86168786, 3.72543606, 4.15926133, 4.58684311, 1.01126713,
       0.61883431, 1.52764296, 4.3252131 , 1.74610151, 4.07453923,
       0.78658403])

In [18]:
list(x)

[np.float64(3.73052330483136),
 np.float64(3.974272304035132),
 np.float64(-3.883016241831432),
 np.float64(-4.19599835057077),
 np.float64(2.2963844273877747),
 np.float64(-4.360639809540672),
 np.float64(-3.3032050595634677),
 np.float64(0.8773772981993346),
 np.float64(-3.9498601739327994),
 np.float64(-1.7977247153502147),
 np.float64(-1.5341728727605881),
 np.float64(-2.5518605707680146),
 np.float64(0.2974926192994838),
 np.float64(-3.5023917939223863),
 np.float64(1.5720763906293849),
 np.float64(-1.7141881738846028),
 np.float64(-4.389560111054371),
 np.float64(1.9748861460651739),
 np.float64(-4.522469598939761),
 np.float64(-1.9450107456534935),
 np.float64(-2.7188951417031797),
 np.float64(-2.609855865987258),
 np.float64(3.971814641480444),
 np.float64(-0.8552868263415974),
 np.float64(4.599716422050776),
 np.float64(-5.245767990180843),
 np.float64(-1.1631340810368949),
 np.float64(-3.0050654208097702),
 np.float64(0.4126049706733319),
 np.float64(-2.351346514268812),
 np.

## Comparing numpy arrays to python lists

In [19]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.000760100s
normalize_py(list(float64)[50000]) -> total time: 0.017016000s


#### Python is slower than numpy in general

In [20]:
%%timeit

np.min(x)

8.1 μs ± 437 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
%%timeit

min(y)

540 μs ± 2.76 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [22]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [23]:
%%timeit

np.min(a)

2.24 μs ± 76.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
%%timeit

min(b)

633 ns ± 18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [25]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [26]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.216509800s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.152017600s
